api/v1/customer/urls.py
from django.urls import path
from api.v1.customer import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('account/', views.account, name='account'),



    path('address/', views.address, name='address'),
    path('address/add/', views.address_add, name='address_add'),
    path('address/edit/<int:id>/', views.address_update, name='address_update'),
    path('address/delete/<int:id>/', views.address_delete, name='address_delete'),



    path('slider/', views.slider, name='slider'),
    path('store/', views.store, name='store'),
    path('store/category/', views.store_category, name='store_category'),
    path('food/category/', views.food_category, name='food_category'),
    path('food/items/', views.food_items, name='food_items'),



    path('single/rest/<int:id>/', views.single_rest, name='single_rest'),
    path('cart/', views.cart, name='cart'),
    path('offer/', views.offer, name='offer'),
    path('order/', views.order, name='order'),
    path('order/item/', views.order_item, name='order_item'),
]

foodz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace="web")),
    path('manager/',include("manager.urls",namespace="manager")),
    path('restaurant/',include("restaurant.urls",namespace="restaurant")),

    path('api/v1/customer/', include('api.v1.customer.urls')),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"



urlpatterns = [
    path('',views.dashboard,name='dashboard'),
    path('profile/',views.profile,name='profile'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),




    path('store_category/',views.store_category,name='store_category'),
    path('store_category_create/',views.store_category_create,name='store_category_create'),
    path('store_category_update/<int:id>/',views.store_category_update,name='store_category_update'),
    path('store_category_delete/<int:id>/',views.store_category_delete,name='store_category_delete'),



    path('store/',views.store,name='store'),
    path('single_store/<int:id>/',views.single_store,name='single_store'),
    path('store_create/',views.store_create,name='store_create'),
    path('store_update/<int:id>/',views.store_update,name='store_update'),
    path('store_delete/<int:id>/',views.store_delete,name='store_delete'),



    path('order/<int:id>/',views.order,name='order'),
    path('order/assign/<int:id>/',views.order_assign,name='order_assign'),
    path('order/accept/<int:id>/',views.order_accept,name='order_accept'),
    path('order/reject/<int:id>/',views.order_reject,name='order_reject'),
    path('order/prepared/<int:id>/',views.order_prepared,name='order_prepared'),
    path('order/picked/<int:id>/',views.order_picked,name='order_picked'),
    path('order/completed/<int:id>/',views.order_completed,name='order_completed'),
    path('order/delete/<int:id>/',views.order_delete,name='order_delete'),




    path('food_category/',views.food_category,name='food_category'),
    path('food_category_create/',views.food_category_create,name='food_category_create'),
    path('food_category_update/<int:id>/',views.food_category_update,name='food_category_update'),
    path('food_category_delete/<int:id>/',views.food_category_delete,name='food_category_delete'),




    path('food_item/',views.food_item,name='food_item'),
    path('food_item_create/',views.food_item_create,name='food_item_create'),
    path('single_food_item/<int:id>',views.single_food_item,name='single_food_item'),
    path('food_item_update/<int:id>/',views.food_item_update,name='food_item_update'),
    path('food_item_delete/<int:id>/',views.food_item_delete,name='food_item_delete'),

    


    path('slider/',views.slider,name='slider'),
    path('slider_create/',views.slider_create,name='slider_create'),
    path('slider_update/<int:id>/',views.slider_update,name='slider_update'),
    path('slider_delete/<int:id>/',views.slider_delete,name='slider_delete'),




    path('carts/',views.carts,name='carts'),
    path('carts/delete/<int:id>/',views.carts_delete,name='carts_delete'),



    path('order/item/',views.order_item,name='order_item'),
    path('order/item/delete/<int:id>/',views.order_item_delete,name='order_item_delete'),



    path('address/',views.address,name='address'),
    path('address/<int:id>/',views.address_delete,name='address_delete'),




    path('offer/',views.offer,name='offer'),
    path('offer/create/',views.offer_create,name='offer_create'),
    path('offer/update/<int:id>/',views.offer_update,name='offer_update'),
    path('offer/delete/<int:id>/',views.offer_delete,name='offer_delete'),




    path('customer/',views.customer,name='customer'),
    path('store/manager',views.store_manager,name='store_manager'),
    path('agent',views.agent,name='agent'),
]

web/urls.py
from django.urls import path
from web import views

app_name = "web"


urlpatterns = [
   path('', views.index, name="index"),
   path('login/', views.login, name="login"),
   path('register/', views.register, name="register"),
   path('logout/', views.logout, name="logout"),
   path('restaurants/<int:id>/', views.restaurants, name="restaurants"),
   
   path('single_restaurant/<int:id>/', views.single_restaurant, name="single_restaurant"),
   path('single_restaurant/cart_add/<int:id>/', views.cart_add, name="cart_add"),
   path('single_restaurant/rest_cart_plus/<int:id>/', views.rest_cart_plus, name="rest_cart_plus"),
   path('single_restaurant/rest_cart_minus/<int:id>/', views.rest_cart_minus, name="rest_cart_minus"),



   path('cart/', views.cart, name="cart"),
   path('cart/cart_plus/<int:id>/', views.cart_plus, name="cart_plus"),
   path('cart/cart_minus/<int:id>/', views.cart_minus, name="cart_minus"),


   path('offers/', views.offers, name="offers"),
   path('offer/apply/<int:id>', views.offer_apply, name="offer_apply"),


   path('checkout/', views.checkout, name="checkout"),
   path('account/', views.account, name="account"),


   path('address/', views.address, name="address"),
   path('add_address/', views.add_address, name="add_address"),
   path('address/edit/<int:id>', views.edit_address, name="edit_address"),
   path('address/delete/<int:id>', views.delete_address, name="delete_address"),
   path('address/select/<int:id>', views.select_address, name="select_address"),

   path('place_order/', views.place_order, name="place_order"),

   path('orders/', views.orders, name="orders"),
   path('order_tracking/<int:id>', views.order_tracking, name="order_tracking"),
]

manager/models.py
from django.db import models

from users.models import User

class Manager(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

api/v1/customer/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken


from django.contrib.auth import authenticate
from users.models import User
from customer.models import Customer
from api.v1.customer.serializers import *



@api_view(['POST'])
@permission_classes ([AllowAny])
def login(request):
    email = request.data.get('email')
    password = request.data.get('password')

    user = authenticate(email=email, password=password)

    if user:
        refresh = RefreshToken.for_user(user)
        response_data = {  
            "status_code": 6000,
            "data": {
                "access": str(refresh.access_token),
            },
            "message": "User is authenticated successfully"
        }
    else:
        response_data = {
            "status_code": 6001,
            "message": "Invalid credentials"
        }

    return Response(response_data)




@api_view(['POST'])
@permission_classes([AllowAny])
def register(request):
    first_name = request.data.get('first_name')
    last_name = request.data.get('last_name')
    email = request.data.get('email')
    password = request.data.get('password')

    if User.objects.filter(email=email).exists():
        response_data = {
            "status_code": 6002,
            "message": "Email already exists"
        }
        return Response(response_data)

    user = User.objects.create_user(
        first_name=first_name,
        last_name=last_name,
        email=email,
        password=password,
        is_customer=True
    )

    user.save()

    customer = Customer.objects.create(
        user=user
    )
    customer.save()

    rfersh = RefreshToken.for_user(user)
    response_data = {
        "status_code": 6000,
        "data": {
            "access": str(rfersh.access_token),
        },
        "message": "User is registered successfully"
    }

    return Response(response_data)
















@api_view(['GET'])
@permission_classes([IsAuthenticated])
def account(request):
    user = request.user
    customer = Customer.objects.get(user=user)

    response_data = {
        "status_code": 6000,
        "data": {
            "first_name": user.first_name,
            "last_name": user.last_name,
            "email": user.email,
            "customer_id": customer.id
        },
        "message": "User account information"
    }
    return Response(response_data)











@api_view(["GET"])
@permission_classes([IsAuthenticated])
def address(request):
    user = request.user
    customer = Customer.objects.get(user=user)


    instances = Address.objects.filter(customer=customer)
    context = {
        "request":request
    }


    serializer = AddressSerializer(instances, many=True, context=context)


    response_data = {
        "status_code":6000,
        "data":serializer.data,
        "message": "Address List"
    }


    return Response(response_data)




@api_view(["POST"])
@permission_classes([IsAuthenticated])
def address_add(request):
    user = request.user
    customer = Customer.objects.get(user=user)


    address = request.data.get('address')
    appartment = request.data.get('appartment')
    landmark = request.data.get('landmark')
    address_type = request.data.get('address_type')

    customer_address = Address.objects.create(
        customer=customer,
        address=address,
        appartment=appartment,
        landmark=landmark,
        address_type=address_type,
    )

    customer_address.save()

    response_data = {
        "status_code":6000,
        "data":{},
        "maessage":"Address Added" 
    }

    return Response(response_data)





@api_view(["PUT"])  
@permission_classes([IsAuthenticated])
def address_update(request,id):
    instance = Address.objects.get(id=id)
    

    address = request.data.get('address')
    appartment = request.data.get('appartment')
    landmark = request.data.get('landmark')
    address_type = request.data.get('address_type')


    instance.address =address
    instance.appartment=appartment
    instance.landmark=landmark
    instance.address_type=address_type

    instance.save()


    response_data = {
        "status_code":6000,
        "data":{},
        "message":"Address Updated"
    }

    return Response(response_data)





@api_view(["DELETE"])
@permission_classes([IsAuthenticated])
def address_delete(request,id):
    instance = Address.objects.get(id=id)
    instance.delete()

    response_data = {
        "status_code":6000,
        "data":{},
        "message":"Address Deleted"
    }

    return Response(response_data)












@api_view(['GET'])
@permission_classes([AllowAny])
def slider(request):
    instances = Slider.objects.all()

    context = {
        "request": request,
    }
    serializer = SliderSerializer(instances, many=True, context=context)

    response_data = {
        'status_code': 6000,
        'data': serializer.data,
        'message': 'slider list retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([AllowAny])
def store(request):

    instances = Store.objects.all()

    context = {
        "request":request,
        
    }
    serializer = StoreSerializer(instances, many=True, context=context)

    response_data = {
        'status_code': 6000,
        'data': serializer.data,
        'message': 'Store list retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([AllowAny])
def store_category(request):
    instances = StoreCategory.objects.all()

    context = {
        "request":request
    }
    serializer = StoreCategorySerializer(instances, many=True, context=context)

    response_data = {
        'status_code': 6000,
        'data': serializer.data,
        'message': 'store category list retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([IsAuthenticated])
def food_category(request):
    instances = FoodCategory.objects.all()

    context = {
        "request": request
    }
    serializer = FoodCategorySerializer(instances, many=True, context=context)

    response_data = {
        'status_code': 6000,
        'data': serializer.data,
        'message': 'Food category list retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([IsAuthenticated])
def food_items(request):
    instances = FoodItem.objects.all()
    context = {
        "request": request
    }
    serializer = FoodItemSerializer(instances, many=True, context=context)
    response_data = {
        'status_code': 6000,
        'data': serializer.data,
        'message': 'Food items list retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([IsAuthenticated])
def single_rest(request, id):

    instance = Store.objects.get(id=id)

    context = {
        "request":request
    }
    seriralizer = StoreSerializer(instance, context=context)
    response_data = {
        'status_code': 6000,
        'data': seriralizer.data,
        'message' : 'single restaurant data retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([IsAuthenticated])
def cart(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    instances = Cart.objects.filter(customer=customer)
    context = {
        "request":request
    }
    serializer = CartSerializer(instances, many=True, context=context)
    response_data = {
        'status_code': 6000,
        'data': serializer.data,
        'message': 'Cart items retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([IsAuthenticated])
def offer(request):

    instances = Offer.objects.all()
    context = {
        "request": request
    }
    serializer = OfferSerializer(instances, many=True, context=context)
    response_data = {
        'status_code': 6000,
        'data': serializer.data,
        'message': 'offer list retrieved successfully'

    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([IsAuthenticated])
def order(request):
    user = request.user
    customer =Customer.objects.get(user=user)
    instances = Order.objects.filter(customer=customer)
    context = {
        "request": request
    }
    serializer = OrderSerializer(instances, many=True,context=context)
    response_data = {
        'status_code': 6000,
        'data':serializer.data,
        'message': 'Order list retrieved successfully'
    }
    return Response(response_data)




@api_view(['GET'])
@permission_classes([IsAuthenticated])
def order_item(request):
    user = request.user
    customer = Customer.objects.get(user=user)
    instances = OrderItem.objects.filter(customer=customer)
    context = {
        "request": request
    }
    serializer = OrderItemSerializer(instances, many=True,context=context)

    response_data = {
        'status_code':6000,
        'data':serializer.data,
        'message':'Order item list retrieved successfully'
    }
    return Response(response_data)

customer/views.py
from django.shortcuts import render

# Create your views here.

templates/manager/food-categories.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}


{% include 'include/manager-header.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Food Categories</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="heading-line">
                                    <h4 class="card-title m-0 p-0">Food Categories</h4>
                                    <a href="{% url 'manager:food_category_create' %}" id="custom-btn">ADD NEW</a>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-bordered zero-configuration" style="border-radius: 14px;">
                                        <thead>
                                            <tr>
                                                <th>NAME</th>
                                                <th>RESTAURENT</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{instance.name}}</td>
                                                <td>{{instance.store}}</td>
                                                <td>
                                                    <a href="{% url 'manager:food_category_update' id=instance.id %}" id="custom-btn">EDIT</a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'manager:food_category_delete' id=instance.id %}" id="custom-btn">DELETE</a>
                                                </td>
                                            </tr>
                                            {% endfor %}


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->


{% endblock %}

templates/manager/index.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}


{% include 'include/manager-header.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div id="overview-container" class="card">
                <h1 class="card-title">Overview</h1>
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <div class="card-body dash-item">
                            <div class="icon-bg">
                                <i class="fa-solid fa-chart-column"></i>
                            </div>
                            <div>
                                <p>Orders</p>
                                <h3>{{orders}}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card-body dash-item">
                            <div class="icon-bg">
                                <i class="fa-solid fa-user-group"></i>
                            </div>
                            <div>
                                <p>Customers</p>
                                <h3>{{customers}}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card-body dash-item">
                            <div class="icon-bg">
                                <i class="fa-solid fa-store"></i>
                            </div>
                            <div>
                                <p>Stores</p>
                                <h3>{{stores}}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6">
                        <div class="card-body dash-item">
                            <div class="icon-bg">
                                <i class="fa-solid fa-coins"></i>
                            </div>
                            <div>
                                <p>Earnings</p>                            
                                <h3>{{earnings}}</h3>  
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            {% if instances %}
                <div class="container-fluid mt-3">

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-body">
                                    <h1 class="card-title" style="padding-bottom: 16px;">Recent Orders</h1>
                                    <div class="active-member">
                                        <div class="table-responsive">
                                            <table class="table table-xs mb-0">
                                                <thead>
                                                    <tr>
                                                        <th>Customer</th>
                                                        <th>Store</th>
                                                        <th>Price</th>
                                                        <th>Delivery</th>
                                                        <th>View</th>
                                                        <th>Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for instance in instances %}
                                                    <tr>
                                                        <td>{{instance.customer.user.first_name}} {{instance.customer.user.last_name}}</td>
                                                        <td>{{instance.store.name}}</td>
                                                        <td>{{instance.total}}</td>
                                                        <td>
                                                            <a href="{% url 'manager:order_assign' id=instance.id %}" id="custom-btn">ASSIGN</a>
                                                        </td>
                                                        <td>
                                                            <a href="{% url 'manager:order' id=instance.id %}" id="custom-btn">VIEW</a>
                                                        </td>
                                                        <td class="text-white">
                                                            {% if instance.status == 'PL' %}
                                                                <a href="{% url 'manager:order_accept' id=instance.id %}" id="custom-green">ACCEPT</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">REJECT</a>
                                                            {% elif instance.status == 'AC' %}
                                                                <a href="{% url 'manager:order_prepared' id=instance.id %}" id="custom-green">SHIPED</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">CANCELL</a>
                                                            {% elif instance.status == 'SH' %}
                                                                <a href="{% url 'manager:order_picked' id=instance.id %}" id="custom-green">ON THE WAY</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">CANCELL</a>
                                                            {% elif instance.status == 'DI' %}
                                                                <a href="{% url 'manager:order_completed' id=instance.id %}" id="custom-green">COMPLETE</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">CANCELL</a>
                                                            {% elif instance.status == 'CA' %}
                                                                <a href="#" id="custom-red">CANCELLED</a>
                                                            {% else %}
                                                                <a style="font-size: 12px;" class="btn-rounded py-2 px-3  mb-1 btn-primary color-white">
                                                                    COMPLETED
                                                                </a>
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                    {% endfor %}
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>                        
                        </div>
                    </div>


                </div>
            {% endif %}
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

        {% endblock %}

templates/manager/offers.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}


{% include 'include/manager-header.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Offers</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="heading-line">
                                    <h4 class="card-title m-0 p-0">Offers</h4>
                                    <a href="{% url 'manager:offer_create' %}" id="custom-btn">ADD NEW</a>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-bordered zero-configuration" style="border-radius: 14px;">
                                        <thead>
                                            <tr>
                                                <th>COUPEN CODE</th>
                                                <th>DESCRIPTION</th>
                                                <th>OFFER</th>
                                                <th>EDITE</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{instance.coupon_code}}</td>
                                                <td>{{instance.description}}</td>
                                                {% if instance.is_percentage %}
                                                    <td>{{instance.offer}}%</td>
                                                {% else %}
                                                    <td>{{instance.offer}}</td>
                                                {% endif %}
                                                <td>
                                                    <a href="{% url 'manager:offer_update' id=instance.id %}" id="custom-btn">EDITE</a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'manager:offer_delete' id=instance.id %}" id="custom-btn">DELETE</a>
                                                </td>
                                            </tr>
                                            {% endfor %}


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->


{% endblock %}