foodz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace="web")),
    path('manager/',include("manager.urls",namespace="manager")),
    path('restaurant/',include("restaurant.urls",namespace="restaurant")),

    path('api/v1/customer/', include('api.v1.customer.urls')),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

restaurant/urls.py
from django.urls import path
from restaurant import views

app_name = "restaurant"


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('add_store/', views.add_store, name='add_store'),
    path('edit_store/<int:id>/', views.edit_store, name='edit_store'),
    path('delete_store/<int:id>/', views.delete_store, name='delete_store'),
 


    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),




    path('food-items/', views.food_items, name='food_items'),
    path('single_food_item/<int:id>/', views.single_food_item, name='single_food_item'),
    path('add_food_item/', views.add_food_item, name='add_food_item'),
    path('edit_food_item/<int:id>/', views.edit_food_item, name='edit_food_item'),
    path('delete_food_item/<int:id>/', views.delete_food_item, name='delete_food_item'),





    path('food-categories/', views.food_categories, name='food_categories'),
    path('add_food_category/', views.add_food_category, name='add_food_category'),
    path('edit_food_category/<int:id>/', views.edit_food_category, name='edit_food_category'),
    path('delete_food_category/<int:id>/', views.delete_food_category, name='delete_food_category'),







    path('orders/', views.orders, name='orders'),
    path('order/<int:id>/',views.order,name='order'),
    path('order/delete/<int:id>/',views.order_delete,name='order_delete'),
]

web/urls.py
from django.urls import path
from web import views

app_name = "web"


urlpatterns = [
   path('', views.index, name="index"),
   path('login/', views.login, name="login"),
   path('register/', views.register, name="register"),
   path('logout/', views.logout, name="logout"),
   path('restaurants/<int:id>/', views.restaurants, name="restaurants"),
   
   path('single_restaurant/<int:id>/', views.single_restaurant, name="single_restaurant"),
   path('single_restaurant/cart_add/<int:id>/', views.cart_add, name="cart_add"),
   path('single_restaurant/rest_cart_plus/<int:id>/', views.rest_cart_plus, name="rest_cart_plus"),
   path('single_restaurant/rest_cart_minus/<int:id>/', views.rest_cart_minus, name="rest_cart_minus"),



   path('cart/', views.cart, name="cart"),
   path('cart/cart_plus/<int:id>/', views.cart_plus, name="cart_plus"),
   path('cart/cart_minus/<int:id>/', views.cart_minus, name="cart_minus"),


   path('offers/', views.offers, name="offers"),
   path('offer/apply/<int:id>', views.offer_apply, name="offer_apply"),


   path('checkout/', views.checkout, name="checkout"),
   path('account/', views.account, name="account"),


   path('address/', views.address, name="address"),
   path('add_address/', views.add_address, name="add_address"),
   path('address/edit/<int:id>', views.edit_address, name="edit_address"),
   path('address/delete/<int:id>', views.delete_address, name="delete_address"),
   path('address/select/<int:id>', views.select_address, name="select_address"),

   path('place_order/', views.place_order, name="place_order"),

   path('orders/', views.orders, name="orders"),
   path('order_tracking/<int:id>', views.order_tracking, name="order_tracking"),
]

restaurant/models.py
from django.db import models

from users.models import User   



class StoreCategory(models.Model):
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='category')

    class Meta:
        db_table = 'restaurant_store_categoy'
        verbose_name = 'store category'
        verbose_name_plural = 'store categories'
        ordering = ['-id']

    def __str__(self):
        return self.name
    

class Store(models.Model):
    name = models.CharField(max_length=256)
    tagline = models.CharField(max_length=256)
    category = models.ForeignKey(StoreCategory, on_delete=models.CASCADE)
    image = models.FileField(upload_to='store')
    rating = models.FloatField()
    time = models.IntegerField()
    offer = models.CharField(max_length=255)


    class Meta:
        db_table = 'restaurant_store'
        verbose_name = 'store'
        verbose_name_plural = 'stores'
        ordering = ['-id']


    def __str__(self):
        return self.name
    


class Slider(models.Model):
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='slide')
    store = models.ForeignKey(Store, on_delete=models.CASCADE)


    class Meta:
        db_table = 'restaurant_slider'
        verbose_name = 'slider'
        verbose_name_plural = 'sliders'
        ordering = ['-id']


    def __str__(self):
        return self.name
    


    


class FoodCategory(models.Model):
    name = models.CharField(max_length=255) 
    store = models.ForeignKey(Store, on_delete=models.CASCADE) 


    class Meta:
        db_table = 'food_category'
        verbose_name = 'food category'
        verbose_name_plural = 'food categories'
        ordering = ['-id']


    def __str__(self):
        return self.name
    



class FoodItem(models.Model):
    name = models.CharField(max_length=255)
    is_veg = models.BooleanField(default=False)
    price = models.IntegerField()
    image = models.FileField(upload_to='fooditems')
    categry = models.ForeignKey(FoodCategory, on_delete=models.CASCADE, related_name='fooditem')


    class Meta:
        db_table = 'food_item'
        verbose_name = 'food item'
        verbose_name_plural = 'food items'
        ordering = ['-id']


    def __str__(self):
        return self.name



class StoreManager(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'restaurant_store_manager'
        verbose_name = 'store manager'
        verbose_name_plural = 'store managers'
        ordering = ['-id']

    def __str__(self):
        return self.user.email

restaurant/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login as login_store, logout as logout_store
from django.contrib.auth.decorators import login_required
from users.models import User
from restaurant.models import *
from customer.models import *
from manager.forms import StoreForm
from main.function import generate_form_errors
from main.decorators import allow_store



from restaurant.models import *
from main.function import generate_form_errors
from main.decorators import allow_store



@login_required(login_url='/restaurant/login')
@allow_store
def dashboard(request):
    user = request.user
    instance = StoreManager.objects.get(user=user).store
    
     
    
    orders = Order.objects.filter(store=instance)
    customers = orders.values('customer').distinct().count()
    fooditems = FoodItem.objects.filter(categry__store=instance).count()
    order_count = orders.count()
    

    earnings = 0
    for order in orders:
        earnings += (order.total - ((5 * order.total) / 100))

    context = {
        'instance': instance,
        'orders': order_count,
        'fooditems': fooditems,
        'earnings': earnings,
        'customers': customers,
    }
    return render(request, 'store/index.html', context=context)




@login_required(login_url='/restaurant/login')
@allow_store
def edit_store(request, id):
    instance = get_object_or_404(Store, id=id)

    if request.method == 'POST':
        form = StoreForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()

            return HttpResponseRedirect(reverse('restaurant:dashboard'))
        
        else:
            message = generate_form_errors(form)
            form = StoreForm(instance=instance)

            context = {
                "message":message,
                "error":True,
                "form":form,
            }
            return render(request, 'store/add-store.html', context=context)
        

    else:
        form = StoreForm(instance=instance)
        context = {
            'form':form
        }

        return render(request, 'store/add-store.html', context=context)


    

@login_required(login_url='/restaurant/login')
@allow_store
def add_store(request):
    user = request.user
    store_det = StoreManager.objects.get(user=user)

    if store_det.store:
        return HttpResponseRedirect(reverse('restaurant:profile'))
    
    else:
        if request.method == 'POST':
            form = StoreForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.save()
                store_det.store = instance
                store_det.save()
                return HttpResponseRedirect(reverse('restaurant:profile'))
            
            else:
                message = generate_form_errors(form)
                form = StoreForm()

                context = {
                    'message':message,
                    'error':True,
                    'form':form,
                }
                return render(request, 'store/add-store.html', context=context)

        else:
            form = StoreForm()
            context = {
                'form':form
            }
            return render(request, 'store/add-store.html', context=context)
    


@login_required(login_url='/restaurant/login')
@allow_store
def delete_store(request,id):
    instance = get_object_or_404(Store, id=id)
    instance.delete()

    return HttpResponseRedirect(reverse('restaurant:dashboard'))



@login_required(login_url='/restaurant/login')
@allow_store
def profile(request):
    user = request.user
    store_details = StoreManager.objects.get(user=user)
    store= store_details.store
    fooditems = FoodItem.objects.filter(categry__store=store).count()
    if store:
        orders = store_details.store.order_set.all().count()
    else:
        orders = 0

    context = {
        'store_details': store_details,
        'fooditems': fooditems,
        'orders': orders,
    }
    return render(request, 'store/profile.html', context=context)


















def register(request):
    
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        password = request.POST.get('password')


        if User.objects.filter(email=email).exists():
            context = {
                "error" : True,
                "message": "Email already exists"
            }
            return render(request, 'store/register.html', context=context)
        

        else:
            user = User.objects.create_user(
                first_name=first_name,
                last_name=last_name,
                email=email,
                password=password,
                is_store=True,
            )
            user.save()
            store_manager = StoreManager.objects.create(
                user=user,
            )
            store_manager.save()
            return HttpResponseRedirect(reverse('restaurant:login'))

    else:
        return render(request, 'store/register.html')


def login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password, is_store=True)
        if user is not None:
            login_store(request, user)
            return HttpResponseRedirect(reverse('restaurant:dashboard'))
        else:
            message = "Invalid email or password"
            context = {
                "message": message,
            }
            return render(request, 'store/login.html', context=context)

    else:
        return render(request, 'store/login.html')


def logout(request):
    logout_store(request)
    return HttpResponseRedirect(reverse('restaurant:login'))















@login_required(login_url='/restaurant/login')
@allow_store
def food_items(request):
    user = request.user
    store_details = StoreManager.objects.get(user=user)
    store = store_details.store
    instances = FoodItem.objects.filter(categry__store=store)

    context = {
        'instances': instances,
    }
    return render(request, 'store/food-items.html', context=context)


@login_required(login_url='/restaurant/login')
@allow_store
def single_food_item(request,id):
    instance = get_object_or_404(FoodItem, id=id)
    context = {
        'instance': instance,
    }
    return render(request, 'store/food-item.html', context=context)


@login_required(login_url='/restaurant/login')
@allow_store
def add_food_item(request):
    user = request.user
    store = StoreManager.objects.get(user=user).store
    food_categories = FoodCategory.objects.filter(store=store)

    if request.method == 'POST':
        name = request.POST.get('fooditem_name')
        price = request.POST.get('price')
        is_veg = request.POST.get('is_veg') == 'on'
        category_id = request.POST.get('category')
        image = request.FILES.get('image')
        categry = get_object_or_404(FoodCategory, id=category_id)

        food_item = FoodItem.objects.create(
            name=name,
            price=price,
            is_veg=is_veg,
            categry=categry,
            image=image,
        )
        food_item.save()
        return HttpResponseRedirect(reverse('restaurant:food_items'))
    
    else:
        context = {
            "food_categories": food_categories
        }
        return render(request,'store/add-food-items.html', context=context)

    

@login_required(login_url='/restaurant/login')
@allow_store
def edit_food_item(request, id):
    instance = get_object_or_404(FoodItem, id=id)
    if request.method == 'POST':
        name = request.POST.get('fooditem_name')
        price = request.POST.get('price')
        is_veg = request.POST.get('is_veg') == 'on'
        category_id = request.POST.get('category')
        image = request.FILES.get('image')
        categry = get_object_or_404(FoodCategory, id=category_id)

        instance.name = name
        instance.price = price
        instance.is_veg = is_veg
        instance.categry = categry
        instance.image = image
        instance.save()
        return HttpResponseRedirect(reverse('restaurant:single_food_item', args=[id]))
    
    else:
        food_categories = FoodCategory.objects.filter(store=instance.categry.store)
        context = {
            'instance': instance,
            'food_categories': food_categories
        }
        return render(request,'store/add-food-items.html', context=context)



@login_required(login_url='/restaurant/login')
@allow_store
def delete_food_item(request, id):
    instance = get_object_or_404(FoodItem, id=id)
    instance.delete()
    return HttpResponseRedirect(reverse('restaurant:food_items'))















@login_required(login_url='/restaurant/login')
@allow_store
def food_categories(request):
    user = request.user
    store = StoreManager.objects.get(user=user).store

    instances = FoodCategory.objects.filter(store=store)
    context = {
        'instances': instances,
    }
    return render(request,'store/food-categories.html', context=context)



@login_required(login_url='/restaurant/login')
@allow_store
def add_food_category(request):
    user = request.user
    store = StoreManager.objects.get(user=user).store

    if request.method == 'POST':
        name = request.POST.get('category_name')
        food_category = FoodCategory.objects.create(
            name=name,
            store=store,
        )
        food_category.save()
        return HttpResponseRedirect(reverse('restaurant:food_categories'))
    
    else:
        return render(request,'store/add-food-categories.html')
    

templates/web/account.html
{% extends 'base/base.html' %}

{% load static %}

{% block container %}


    <header class="h-[80px] shadow-md">
        <section class="wrapper h-full flex justify-start items-center">
            <div class="w-[30%] md:w-[38%] lg:w-[42%]">
                <a href="{% url 'web:index' %}">
                    <img src="{% static 'web/images/arrow.png' %}" alt="" class="w-[16px] md:w-[25px]">
                </a>
            </div>
            <div class="w-[70%] md:w-[62%] lg:w-[58%]">
                <h1 class="text-[26px] md:text-[34px] font-bold text-[#515151]">Account</h1>
            </div>
        </section>
    </header>



    <section class="py-10">
        <section class="wrapper">
            <div class="grid grid-cols-1 lg:grid-cols-3 gap-7">
                <div class="col-span-1">
                    <div class="flex justify-start items-center rounded-lg border p-6 mb-6">
                        <div class="mb-3 w-[30%] mr-3">
                            <img src="{% static 'web/images/man.png' %}" alt="" class="rounded-lg ">
                        </div>

                        <div class="">
                            <p class="text-[#515151] text-[15px] font-semibold mb-2">{{customer.user.first_name}} {{customer.user.last_name}}</p>
                            <p class="text-[#515151] text-[15px] font-semibold">{{customer.user.email}}</p>
                        </div>
                    </div>

                    <div class="px-12">
                        <a href="{% url 'web:address' %}" class="bg-[#2AC489] flex justify-start items-center py-2 px-6 border-2 hover:bg-[#67c09e] rounded-lg mb-5 ">
                            <img src="{% static 'web/images/address.png' %}" alt="" class="w-[22px] mr-4">
                            <p class="text-[16px] text-white font-semibold">Manage Address</p>
                        </a>

                        <a href="{% url 'web:cart' %}" class="bg-[#2AC489] flex justify-start items-center py-2 px-6 border-2 hover:bg-[#67c09e] rounded-lg mb-5 ">
                            <img src="{% static 'web/images/cart2.png' %}" alt="" class=" invert mr-4">
                            <p class="text-[16px] text-white font-semibold">Cart</p>
                        </a>

                        <a href="{% url 'web:orders' %}" class="bg-[#2AC489] flex justify-start items-center py-2 px-6 border-2 hover:bg-[#67c09e] rounded-lg mb-5 ">
                            <img src="{% static 'web/images/cart.png' %}" alt="" class="w-[22px] mr-4">
                            <p class="text-[16px] text-white font-semibold">Orders</p>
                        </a>

                        <a href="{% url 'web:logout' %}" class="bg-[#2AC489] flex justify-start items-center py-2 px-6 border-2 hover:bg-[#67c09e] rounded-lg mb-5 ">
                            <img src="{% static 'web/images/logout.png' %}" alt="" class="w-[22px] mr-4">
                            <p class="text-[16px] text-white font-semibold">Logout</p>
                        </a>
                    </div>
                                       
                </div>

                <div class="col-span-2">
                    <h2 class="mb-5 text-[#515151] text-[16px] md:text-[22px] font-bold">Recent Orders</h2>
                    <div class="md:grid md:grid-cols-2 gap-6">
                        {% for item in order_item_count %}
                            <div class="rounded-lg border p-6 shadow-md mb-6">
                                <div class="flex justify-between items-start border-b-2 pb-2 mb-3">
                                    <div class="flex justify-start items-start">
                                        <img src="{{item.order.store.image.url}}" alt="" class="w-[18%] rounded-lg mr-3">

                                        <div class="w-[70%]">
                                            <h3 class="text-[#515151] text-[15px] font-semibold mb-2">{{item.order.store.name}}</h3>
                                            <p class="text-[#515151] text-[14px] font-semibold">₹ {{item.order.total}} | {{item.count}} items</p>
                                        </div>
                                    </div>

                                    <span class="text-[#515151] text-[14px] font-semibold underline">
                                        #{{item.order.order_id}}
                                    </span>
                                </div>

                                <div class="flex justify-between items-center">
                                    <a href="{% url 'web:order_tracking' item.order.id %}"><button class=" py-2 px-4 bg-[#2AC489] rounded-md hover:bg-[#67c09e] text-[12px] md:text-[15px] text-white font-semibold">TRACK ORDER</button></a>
                                    <p class="px-3 py-1 rounded-full text-[15px] font-semibold {% if item.order.status == 'CO' %}bg-green-200 text-green-800{% elif item.order.status == 'SH' or item.order.status == 'DI' %}bg-blue-200 text-blue-800{% else %}bg-yellow-100 text-yellow-700{% endif %}">
                                        {% if item.order.status == 'PL' %}
                                            Prepairing
                                        {% elif item.order.status == 'AC' %}
                                            Prepared
                                        {% elif item.order.status == 'SH' %}
                                            Shiped
                                        {% elif item.order.status == 'DI' %}
                                            On The Way
                                        {% elif item.order.status == 'CA' %}
                                            Cancelled
                                        {% else %}
                                            Delivered
                                        {% endif %}
                                    </p>
                                </div>
                            </div>                      
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </section>    










{% endblock %}    

templates/web/cart.html
{% extends 'base/base.html' %}

{% load static %}

{% block container %}




    
    {% if carts %}

        <header class="h-[80px] shadow-md">
            <section class="wrapper h-full flex justify-start items-center">
                <div class="w-[30%] md:w-[38%] lg:w-[42%]">
                    <a href="{% url 'web:single_restaurant' id=store.id %}">
                        <img src="{% static 'web/images/arrow.png' %}" alt="" class="w-[16px] md:w-[25px]">
                    </a>
                </div>

                <div class="w-[70%] md:w-[62%] lg:w-[58%]">
                    <h1 class="text-[26px] md:text-[34px] font-bold text-[#515151]">Cart</h1>
                </div>
            </section>
        </header>



        <section class="py-10 lg:px-[25%]">
            <section class="wrapper">
                <div class="rounded-lg shadow-lg border p-5">
                    <a href="" class="flex justify-start items-start">
                        <img src="{{store.image.url}}" alt="" class="w-[40%] md:w-[30%] rounded-lg mr-6">
                        <div class="w-[60%] md:w-[70%]">
                            <h3 class="text-[#515151] text-[16px] font-semibold mb-2">{{store.name}}</h3>
                            <p class="text-[#515151] text-[12px]">{{store.tagline}}</p>
                            <div class="flex justify-start items-center mt-5 mb-3">
                                <span class="flex justify-start items-center text-[#515151] text-[14px] font-semibold mr-4">
                                    <img src="{% static 'web/images/star.png' %}" alt="image" class="w-[16px] mr-2">
                                    {{store.rating}}
                                </span>
                                <span class="flex justify-start items-center text-[#515151] text-[14px] font-semibold">
                                    <img src="{% static 'web/images/clock.png' %}" alt="image" class="w-[16px] mr-2">
                                    {{store.time}} min
                                </span>
                            </div>
                        </div>
                    </a>                   
                </div>
            </section>
        </section>



        <section class="py-10 lg:px-[25%] mb-14 lg:mb-0">
            <section class="wrapper">
                <div class="rounded-lg shadow-md border p-5 mb-5">
                    <h2 class="text-[#515151] text-[16px] font-semibold border-b pb-2">ITEM IN CART</h2>
                    {% for cart in carts %}
                    <div class="mt-3 flex justify-between items-center border-b pb-2 mb-3">
                        <div class="">
                            <p class="text-[#515151] text-[14px] font-semibold">{{cart.product}}</p>
                            <p class="text-[14px] font-bold">₹ {{cart.amnt}}</p>
                        </div>
                        <div class="border rounded-lg md:mr-24">
                            <a href="{% url 'web:cart_minus' id=cart.id %}"><button class="py-2 px-3 bg-[#2AC489] rounded-s-lg text-white font-semibold">-</button></a>
                            <span class="ml-3 mr-3">{{cart.qty}}</span>
                            <a href="{% url 'web:cart_plus' id=cart.id %}"><button class="py-2 px-3 bg-[#2AC489] rounded-e-lg text-white font-semibold">+</button></a>
                        </div>
                    </div>
                    {% endfor %}
                </div>



                <div class="rounded-lg shadow-md border p-5 mb-5">
                    <div class="mt-3 flex justify-between items-center border-b pb-5 mb-3">
                        <div class="">
                            <input type="text" placeholder="Coupen Code" class="text-[16px] font-semibold border-none outline-none">
                        </div>
                        <div class="rounded-lg">
                            <button class="py-2 px-8 md:px-12 bg-[#2AC489] rounded-lg mr-5 text-white font-semibold">Apply</button>
                        </div>
                    </div>

                    <div class="mt-3 flex justify-start items-center mb-2">
                        <img src="{% static 'web/images/discount.png' %}" alt="" class="w-[19px] mr-4" >
                        <a href="{% url 'web:offers' %}" class=""><p class="text-red-500 font-bold">View All Offers</p></a>
                    </div>             
                </div>




                <div class="rounded-lg shadow-md border p-5 mb-5">
                    <h2 class="text-[#515151] text-[16px] font-bold">BILL DETAILS</h2>
                    <div class="mt-3 flex justify-between items-center border-b pb-2 mb-3">
                        <p class="text-[#515151] text-[14px] font-semibold">Item Total</p>
                        <p class="text-[14px] font-bold text-[#515151]">₹ {{sub_total}}</p>
                    </div>

                    <div class="mt-3 flex justify-between items-center border-b pb-2 mb-3">
                        <p class="text-[#515151] text-[14px] font-semibold">Offer Applied</p>
                        <p class="text-[14px] font-bold text-[#515151]">-₹ {{cart_bill.offer_amnt}}</p>
                    </div>

                    <div class="mt-3 flex justify-between items-center border-b pb-2 mb-3">
                        <p class="text-[#515151] text-[14px] font-semibold">Delivery Charges (4km)</p>
                        <p class="text-[14px] font-bold text-[#515151]">₹ {{cart_bill.delivery_charge}}</p>
                    </div>

                    <div class="mt-3 flex justify-between items-center mb-3">
                        <p class="text-[14px] font-semibold">To Pay</p>
                        <p class="text-[14px] font-bold">₹ {{total}}</p>
                    </div>
                </div>



                {% if selected_address %}
                    <div class="rounded-lg shadow-md border p-5 mb-5">
                        <div class="mt-3 border-b pb-5 mb-3">
                            <p class="text-[#515151] font-bold">DELIVER TO</p>
                        </div>

                        <div class="mt-3 flex justify-between items-center mb-3">
                            <div class="">
                                <p class="text-[#515151] text-[16px] font-semibold">{{selected_address.address}}</p>
                            </div>
                            <a href="{% url 'web:address' %}" class="rounded-lg">
                                <button class="py-2 px-6 md:px-12 bg-[#2AC489] rounded-lg mr-5 text-white font-semibold">CHANGE</button>
                            </a>
                        </div>
                    </div>

                    <a href="{% url 'web:checkout' %}" class="bg-red-500 px-4 rounded-xl h-[50px] flex justify-center items-center mb-6 cursor-pointer">
                        <p class="text-[16px] text-white font-semibold">CONTINUE</p>   
                    </a>
                {% else %}
                    <div class="mt-5 flex justify-between items-center rounded-lg shadow-md border p-5 mb-5">
                        <div class="">
                            <p class="text-[#515151] text-[16px] font-semibold">Add address</p>
                        </div>
                        <a href="{% url 'web:address' %}" class="rounded-lg">
                            <button class="py-2 px-6 md:px-12 bg-[#2AC489] rounded-lg mr-5 text-white font-semibold">ADD</button>
                        </a>
                    </div>

                    <a href="" class="bg-red-500 px-4 rounded-xl h-[50px] flex justify-center items-center mb-6 cursor-not-allowed">
                        <p class="text-[16px] text-[#b6b4b4] font-semibold">CONTINUE</p>   
                    </a>
                {% endif %}
                
                




                
            </section>
        </section>

    {% else %}

        {% include 'include/header.html' %}

        <h3 class="py-40 h-screen text-center text-[30px] font-semibold text-red-500">Cart Not Found</h3>

        {% include 'include/footer.html' %}
    
        
    {% endif %}    


    

{% endblock %}