foodz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace="web")),
    path('manager/',include("manager.urls",namespace="manager")),
    path('restaurant/',include("restaurant.urls",namespace="restaurant")),

    path('api/v1/customer/', include('api.v1.customer.urls')),
]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"



urlpatterns = [
    path('',views.dashboard,name='dashboard'),
    path('profile/',views.profile,name='profile'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),




    path('store_category/',views.store_category,name='store_category'),
    path('store_category_create/',views.store_category_create,name='store_category_create'),
    path('store_category_update/<int:id>/',views.store_category_update,name='store_category_update'),
    path('store_category_delete/<int:id>/',views.store_category_delete,name='store_category_delete'),



    path('store/',views.store,name='store'),
    path('single_store/<int:id>/',views.single_store,name='single_store'),
    path('store_create/',views.store_create,name='store_create'),
    path('store_update/<int:id>/',views.store_update,name='store_update'),
    path('store_delete/<int:id>/',views.store_delete,name='store_delete'),



    path('order/<int:id>/',views.order,name='order'),
    path('order/assign/<int:id>/',views.order_assign,name='order_assign'),
    path('order/accept/<int:id>/',views.order_accept,name='order_accept'),
    path('order/reject/<int:id>/',views.order_reject,name='order_reject'),
    path('order/prepared/<int:id>/',views.order_prepared,name='order_prepared'),
    path('order/picked/<int:id>/',views.order_picked,name='order_picked'),
    path('order/completed/<int:id>/',views.order_completed,name='order_completed'),
    path('order/delete/<int:id>/',views.order_delete,name='order_delete'),




    path('food_category/',views.food_category,name='food_category'),
    path('food_category_create/',views.food_category_create,name='food_category_create'),
    path('food_category_update/<int:id>/',views.food_category_update,name='food_category_update'),
    path('food_category_delete/<int:id>/',views.food_category_delete,name='food_category_delete'),




    path('food_item/',views.food_item,name='food_item'),
    path('food_item_create/',views.food_item_create,name='food_item_create'),
    path('single_food_item/<int:id>',views.single_food_item,name='single_food_item'),
    path('food_item_update/<int:id>/',views.food_item_update,name='food_item_update'),
    path('food_item_delete/<int:id>/',views.food_item_delete,name='food_item_delete'),

    


    path('slider/',views.slider,name='slider'),
    path('slider_create/',views.slider_create,name='slider_create'),
    path('slider_update/<int:id>/',views.slider_update,name='slider_update'),
    path('slider_delete/<int:id>/',views.slider_delete,name='slider_delete'),




    path('carts/',views.carts,name='carts'),
    path('carts/delete/<int:id>/',views.carts_delete,name='carts_delete'),



    path('order/item/',views.order_item,name='order_item'),
    path('order/item/delete/<int:id>/',views.order_item_delete,name='order_item_delete'),



    path('address/',views.address,name='address'),
    path('address/<int:id>/',views.address_delete,name='address_delete'),




    path('offer/',views.offer,name='offer'),
    path('offer/create/',views.offer_create,name='offer_create'),
    path('offer/update/<int:id>/',views.offer_update,name='offer_update'),
    path('offer/delete/<int:id>/',views.offer_delete,name='offer_delete'),




    path('customer/',views.customer,name='customer'),
    path('store/manager',views.store_manager,name='store_manager'),
    path('agent',views.agent,name='agent'),
]

restaurant/urls.py
from django.urls import path
from restaurant import views

app_name = "restaurant"


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('add_store/', views.add_store, name='add_store'),
    path('edit_store/<int:id>/', views.edit_store, name='edit_store'),
    path('delete_store/<int:id>/', views.delete_store, name='delete_store'),
 


    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),




    path('food-items/', views.food_items, name='food_items'),
    path('single_food_item/<int:id>/', views.single_food_item, name='single_food_item'),
    path('add_food_item/', views.add_food_item, name='add_food_item'),
    path('edit_food_item/<int:id>/', views.edit_food_item, name='edit_food_item'),
    path('delete_food_item/<int:id>/', views.delete_food_item, name='delete_food_item'),





    path('food-categories/', views.food_categories, name='food_categories'),
    path('add_food_category/', views.add_food_category, name='add_food_category'),
    path('edit_food_category/<int:id>/', views.edit_food_category, name='edit_food_category'),
    path('delete_food_category/<int:id>/', views.delete_food_category, name='delete_food_category'),







    path('orders/', views.orders, name='orders'),
    path('order/<int:id>/',views.order,name='order'),
    path('order/delete/<int:id>/',views.order_delete,name='order_delete'),
]

web/urls.py
from django.urls import path
from web import views

app_name = "web"


urlpatterns = [
   path('', views.index, name="index"),
   path('login/', views.login, name="login"),
   path('register/', views.register, name="register"),
   path('logout/', views.logout, name="logout"),
   path('restaurants/<int:id>/', views.restaurants, name="restaurants"),
   
   path('single_restaurant/<int:id>/', views.single_restaurant, name="single_restaurant"),
   path('single_restaurant/cart_add/<int:id>/', views.cart_add, name="cart_add"),
   path('single_restaurant/rest_cart_plus/<int:id>/', views.rest_cart_plus, name="rest_cart_plus"),
   path('single_restaurant/rest_cart_minus/<int:id>/', views.rest_cart_minus, name="rest_cart_minus"),



   path('cart/', views.cart, name="cart"),
   path('cart/cart_plus/<int:id>/', views.cart_plus, name="cart_plus"),
   path('cart/cart_minus/<int:id>/', views.cart_minus, name="cart_minus"),


   path('offers/', views.offers, name="offers"),
   path('offer/apply/<int:id>', views.offer_apply, name="offer_apply"),


   path('checkout/', views.checkout, name="checkout"),
   path('account/', views.account, name="account"),


   path('address/', views.address, name="address"),
   path('add_address/', views.add_address, name="add_address"),
   path('address/edit/<int:id>', views.edit_address, name="edit_address"),
   path('address/delete/<int:id>', views.delete_address, name="delete_address"),
   path('address/select/<int:id>', views.select_address, name="select_address"),

   path('place_order/', views.place_order, name="place_order"),

   path('orders/', views.orders, name="orders"),
   path('order_tracking/<int:id>', views.order_tracking, name="order_tracking"),
]

templates/store/food-categories.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}


{% include 'include/store-header.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Food Categories</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="heading-line">
                                    <h4 class="card-title m-0 p-0">Food Categories</h4>
                                    <a href="{% url 'restaurant:add_food_category' %}" id="custom-btn">ADD NEW</a>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-bordered zero-configuration" style="border-radius: 14px;">
                                        <thead>
                                            <tr>
                                                <th>NAME</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{instance.name}}</td>
                                                <td>
                                                    <a href="{% url 'restaurant:edit_food_category' id=instance.id %}" id="custom-btn">EDIT</a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'restaurant:delete_food_category' id=instance.id %}" id="custom-btn">DELETE</a>
                                                </td>
                                            </tr>
                                            {% endfor %}


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->


{% endblock %}

templates/store/food-item.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}


{% include 'include/manager-header.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Food Items</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Food Item</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Food Item</h4>
                                <div class="table-responsive">
                                    <table class="table header-border">
                                        <thead>
                                            <tr>
                                                <th scope="col">IMAGE</th>
                                                <th scope="col">NAME</th>
                                                <th scope="col">PRICE</th>
                                                <th scope="col">VEG/NON VEG</th>
                                                <th scope="col">CATEGORY</th>
                                                <th scope="col">EDIT</th>
                                                <th scope="col">DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <img src="{{instance.image.url}}" alt="image" class="logo-image">
                                                </td>
                                                <td>{{instance.name}}</td>
                                                <td>{{instance.price}}</td>
                                                {% if instance.is_veg %}
                                                    <td class="badge badge-success px-3" style="margin-top: 2rem; margin-left: 2rem;">VEG</td>
                                                {% else %}
                                                    <td class="badge badge-danger px-2" style="margin-top: 2rem; margin-left: 2rem;">Non Veg</td>
                                                {% endif %}
                                                <td>{{instance.categry}}</td>
                                                <td>
                                                    <a href="{% url 'restaurant:edit_food_item' id=instance.id %}" id="custom-btn">EDIT</a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'restaurant:delete_food_item' id=instance.id %}" id="custom-btn">DELETE</a>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->


{% endblock %}

templates/store/food-items.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}


{% include 'include/store-header.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Food Items</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="heading-line">
                                    <h4 class="card-title m-0 p-0">Food Items</h4>
                                    <a href="{% url 'restaurant:add_food_item' %}" id="custom-btn">ADD NEW</a>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-bordered zero-configuration" style="border-radius: 14px;">
                                        <thead>
                                            <tr>
                                                <th>IMAGE</th>
                                                <th>NAME</th>
                                                <th>VIEW</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>
                                                    <img src="{{instance.image.url}}" alt="image" class="logo-image">
                                                </td>
                                                <td>{{instance.name}}</td>
                                                <td>
                                                    <a href="{% url 'restaurant:single_food_item' id=instance.id %}" id="custom-btn">VIEW</a>
                                                </td>
                                                <td>
                                                    <a href="{% url 'restaurant:delete_food_item' id=instance.id %}" id="custom-btn">DELETE</a>
                                                </td>
                                            </tr>
                                            {% endfor %}


                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->


{% endblock %}

templates/store/login.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}

    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>

    


    <section class="">
        <div class="login-form-bg h-100" style="margin-top: 150px;">
            <div class="container h-100">
                <div class="row justify-content-center h-100">
                    <div class="col-xl-6">
                        <div class="form-input-content">
                            <div class="card login-form mb-0">
                                <div class="card-body pt-5">
                                    <a class="text-center" href="index.html"> <h4>Store Login</h4></a>
            
                                    <form class="mt-5 mb-5 login-input" method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <input type="email" name="email" class="form-control" placeholder="Email" style="padding: 0 10px;">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" name="password" class="form-control" placeholder="Password" style="padding: 0 10px;">
                                        </div>
                                        <button class="btn login-form__btn submit w-100" type="submit">Sign In</button>
                                    </form>
                                    <p class="mt-5 login-form__footer">Dont have account? <a href="{% url 'restaurant:register' %}" class="text-primary">Sign Up</a> now</p>
                                    {% if message %}
                                        <div class="alert alert-danger">{{ message }}</div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/store/orders.html
{% extends "base/manager-base.html" %} {% block container %} {% load static %}


{% include 'include/store-header.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Orders</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            {% if instances %}
                <div class="container-fluid mt-3">

                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-body">
                                    <h1 class="card-title" style="padding-bottom: 16px;">Orders</h1>
                                    <div class="active-member">
                                        <div class="table-responsive">
                                            <table class="table table-xs mb-0">
                                                <thead>
                                                    <tr>
                                                        <th>Customer</th>
                                                        <th>Store</th>
                                                        <th>Price</th>
                                                        <th>View</th>
                                                        <th>Action</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for instance in instances %}
                                                    <tr>
                                                        <td>{{instance.customer.user.first_name}} {{instance.customer.user.last_name}}</td>
                                                        <td>{{instance.store.name}}</td>
                                                        <td>{{instance.total}}</td>
                                                        <td>
                                                            <a href="{% url 'restaurant:order' id=instance.id %}" id="custom-btn">VIEW</a>
                                                        </td>
                                                        <td class="text-white">
                                                            {% if instance.status == 'PL' %}
                                                                <a href="{% url 'manager:order_accept' id=instance.id %}" id="custom-green">ACCEPT</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">REJECT</a>
                                                            {% elif instance.status == 'AC' %}
                                                                <a href="{% url 'manager:order_prepared' id=instance.id %}" id="custom-green">SHIPED</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">CANCELL</a>
                                                            {% elif instance.status == 'SH' %}
                                                                <a href="{% url 'manager:order_picked' id=instance.id %}" id="custom-green">ON THE WAY</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">CANCELL</a>
                                                            {% elif instance.status == 'DI' %}
                                                                <a href="{% url 'manager:order_completed' id=instance.id %}" id="custom-green">COMPLETE</a>
                                                                <br> <br>
                                                                <a href="{% url 'manager:order_reject' id=instance.id %}" id="custom-red">CANCELL</a>
                                                            {% elif instance.status == 'CA' %}
                                                                <a href="#" id="custom-red">CANCELLED</a>
                                                            {% else %}
                                                                <a style="font-size: 12px;" class="btn-rounded py-2 px-3  mb-1 btn-primary color-white">
                                                                    COMPLETED
                                                                </a>
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                    {% endfor %}
                                                    
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>                        
                        </div>
                    </div>


                </div>
            {% endif %}
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->


{% endblock %}

templates/store/profile.html
{% extends "base/manager-base.html" %} {% load static %} {% block container %} 

    {% include 'include/store-header.html' %}

    <div class="content-body">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-xl-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="media align-items-center mb-5">
                                <img class="mr-3" src="{% static 'images/user/form-user.png' %}" width="80" height="80" alt="">
                                <div class="media-body">
                                    <h3 class="mb-0">{{store_details.user.first_name}} {{store_details.user.last_name}}</h3>
                                </div>
                            </div>
                            <div class="row">
                                <ul class="card-profile__info col-12 col-md-6">
                                    <li><strong class="text-dark mr-4">Email :</strong> <span>{{store_details.user.email}}</span></li>
                                </ul>

                                <ul class="text-center col-12 col-md-6">
                                    <li><a href="{% url 'restaurant:logout' %}"><button class="btn btn-danger px-5">LOGOUT</button></a></li>
                                </ul>
                            </div>
                            
                        </div>
                    </div>  
                </div>
                {% if store_details.store %}
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="media align-items-center mb-4">
                                    <img class="mr-3" src="{{store_details.store.image.url}}" width="80" height="80" alt="" style="border-radius: 20px;">
                                    <div class="media-body">
                                        <h3 class="mb-0">{{store_details.store.name}}</h3>
                                    </div>
                                </div>
                                
                                <div class="row mb-5">
                                    <div class="col">
                                        <div class="card card-profile text-center">
                                            <span class="mb-1 text-primary"><i class="fa-solid fa-store"></i></span>
                                            <h3 class="mb-0">{{fooditems}}</h3>
                                            <p class="text-muted px-4">Food Items</p>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="card card-profile text-center">
                                            <span class="mb-1 text-warning"><i class="fa-solid fa-chart-column"></i></span>
                                            <h3 class="mb-0">{{orders}}</h3>
                                            <p class="text-muted">Orders</p>
                                        </div>
                                    </div>
                                </div>
                                <h4>About</h4>
                                <p class="text-muted">{{store_details.store.tagline}}</p>
                                <ul class="card-profile__info">
                                    <li class="mb-1"><strong class="text-dark mr-4"><img src="{% static 'web/images/star.png' %}" alt="image" style="width: 16px; margin-right: 0.2rem;"></strong> <span>{{store_details.store.rating}}</span></li>
                                    <li><strong class="text-dark mr-4"><img src="{% static 'web/images/clock.png' %}" alt="image" style="width: 16px; margin-right: 0.2rem;"></strong> <span>{{store_details.store.time}} min</span></li>
                                </ul>
                                
                                <div class="row mb-5 mt-5">
                                    <div class="col text-center">
                                        <a href="{% url 'restaurant:edit_store' id=store_details.id %}"><button class="btn btn-primary px-5">EDITE</button></a>
                                    </div>
                                    <div class="col text-center">
                                        <a href="{% url 'restaurant:delete_store' id=store_details.id %}"><button class="btn btn-danger px-5">DELETE</button></a>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                {% else %}
                    <div class="row mb-5 mt-5">
                        <div class="col text-center">
                            <a href="{% url 'restaurant:add_store' %}"><button class="btn btn-primary px-5">ADD STORES</button></a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}